# Generated by Django 4.0.3 on 2022-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='Email_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
