# Generated by Django 4.0.3 on 2022-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_register1_flat_no_register1_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='Phone_Number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
