# Generated by Django 4.0.3 on 2022-03-09 01:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register1_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='Country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
