# Generated by Django 4.0.3 on 2022-03-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register1_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='Phone_Number',
            field=models.IntegerField(blank=True),
        ),
    ]
