# Generated by Django 4.0.3 on 2022-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_register1_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='Upload_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
