# Generated by Django 4.0.3 on 2022-03-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_register1_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='Gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register1',
            name='Phone_Number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
